### ISSUE TITLE
Android file upload does not work

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#270]
Hey,
when uploading a file to a document with built Android app just nothing happens. Sismics does not show any error. I already double checked permissions of the App in android system config. When i upload a file accessing sismics docs the web browser everything is fine. In the App i can view the uploaded files and i am able to delete them as well.

I am using the current master branch to build /docs-android with Android SDK and provided gradlew tool

Any idea?

**Comment by jendib** [comment]
I admit I almost never use the Android app to add new files (only to view), so there may be an issue here. Will take a look.

**Comment by Freekers** [comment]
Where can I download the Android app? I cannot find it in the Play store.

**Comment by Freekers** [comment]
Thanks for replying. Ah, if you could do that, that would be awesome. Thanks!

**Comment by vmario89** [comment]
Hey dude,
please have a look at https://leyghis.de/2019/01/11/how-to-compile-sismics-docs-android-application/
I created a fresh blog and made my first posting :-)

**Comment by Freekers** [comment]
Awesome! I'm going to try it out this Sunday. Thanks!

**Comment by vmario89** [comment]
Hey, belonging to this issue, the stack trace is:

E/FileUploadService: Error uploading the file
    java.lang.SecurityException: Permission Denial: startForeground from pid=22043, uid=10242 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5176)
        at android.app.Service.startForeground(Service.java:701)
        at com.sismics.docs.service.FileUploadService.onStart(FileUploadService.java:114)
        at com.sismics.docs.service.FileUploadService.onHandleIntent(FileUploadService.java:65)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:10275)
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1291)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:969)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:22133)
        at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:10501)


https://stackoverflow.com/questions/52382710/permission-denial-startforeground-requires-android-permission-foreground-servic

**Comment by vmario89** [comment]
Hey, the issue was not fixed for my device. I deployed the newest compiled commit to my phone. There when uploading some file why running the app in debug mode, an error stack is thrown:

> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sismics.docs, PID: 14697
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2050)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

The permissions are set (sorry they are german):
![grafik](https://user-images.githubusercontent.com/5631071/51808795-dd9df200-2298-11e9-93ea-75f99164ee39.png)
menas full network access - show network connections - show wifi connections - deactivate standby mode - allow to run in foreground

**Comment by Freekers** [comment]
> 
> 
> Hey dude,
> please have a look at https://leyghis.de/2019/01/11/how-to-compile-sismics-docs-android-application/
> I created a fresh blog and made my first posting :-)

I'm very late to the party (1 year to be exact) but this link no longer works. It seems the document has moved to: https://wiki.fablabchemnitz.de/display/FCT/Teedy+1.8+App+for+Android

I can confirm that the instructions above work perfectly :) I was able to build/compile the Teedy Android APK from source and install it on my phone using your instructions. I greatly appreciate your time and effort to write these instructions and I apologize that it took me a year to do so.

For those of you looking for a pre-built APK, here you go (use at your own risk): 
[teedy_v1.0_build1_signed.apk.zip](https://github.com/sismics/docs/files/4123157/teedy_v1.0_build1_signed.apk.zip)
