### ISSUE TITLE
Can't send password reset email

### ISSUE THREAD

**Issue by ahmedmagdiosman** [sismics/docs#353]
I'm having trouble sending password reset emails using an Outlook email. I'm using the exact same settings for different deployments (Healthchecks, Grafana, etc..) and they work with no issues.

Email settings:
* SMTP Host:  smtp.office365.com
* STMP Port: 587
* Username: example@outlook.com
* Password: xxx
* Sender email: example@outlook.com

Here's the error:
```
06 Sep 2019 18:11:44,665 ERROR com.sismics.util.EmailUtil.sendEmail(EmailUtil.java:161) Error sending email with template=password_recovery to user UserDto{id=xxxx, username=user, email=user@outlook.com}
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.office365.com:587
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)
	at org.apache.commons.mail.Email.send(Email.java:1496)
	at com.sismics.util.EmailUtil.sendEmail(EmailUtil.java:159)
	at com.sismics.util.EmailUtil.sendEmail(EmailUtil.java:175)
	at com.sismics.docs.core.listener.async.PasswordLostAsyncListener.lambda$on$0(PasswordLostAsyncListener.java:49)
	at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:47)
	at com.sismics.docs.core.listener.async.PasswordLostAsyncListener.on(PasswordLostAsyncListener.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM6P191CA0047.EURP191.PROD.OUTLOOK.COM]
````

My first guess is that there's no option for TLS/SSL authentication which is required by most email providers, but I really have no idea where that needs to be changed in the codebase.

Any help is appreciated :)

**Comment by jendib** [comment]
TLS is supported. It seems to be a issue specific to Office 365. I found this: https://stackoverflow.com/questions/30342884/5-7-57-smtp-client-was-not-authenticated-to-send-anonymous-mail-during-mail-fr

It seems that the FROM address is not recognized. What did you put in Admin > Configuration > Sender e-mail?

**Comment by ahmedmagdiosman** [comment]
I've put the same username (i.e. the email address): example@outlook.com

**Comment by jendib** [comment]
And you configured the SMTP username and password I guess?

**Comment by jendib** [comment]
Also, please see: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_winother/client-was-not-authenticated-to-send-anonymous/d405bcb0-f40c-42fa-b1b2-477597100123

Microsoft say you cannot use smtp.office365.com.

**Comment by ahmedmagdiosman** [comment]
> Email settings:
> 
> * SMTP Host:  smtp.office365.com
> * STMP Port: 587
> * Username: [example@outlook.com](mailto:example@outlook.com)
> * Password: xxx
> * Sender email: [example@outlook.com](mailto:example@outlook.com)
> 

Yeah I've put my settings in the initial issue comment (just anonymized).





> Also, please see: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_winother/client-was-not-authenticated-to-send-anonymous/d405bcb0-f40c-42fa-b1b2-477597100123
> 
> Microsoft say you cannot use smtp.office365.com.

I'm using this smtp host for all my other services. It's the recommended method from Microsoft: https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3

The method you linked is for direct send which is limited to sending emails to addresses within the same domain.

**Comment by ahmedmagdiosman** [comment]
I tried anyway to send an email using direct send, but it's getting blocked since my IP is listed on Spamhaus as a dial-IP (i.e. my ISP is blocking direct email send from residential IPs).

**Comment by jendib** [comment]
I found somewhere else that adding "-Dmail.smtp.starttls.enable=true" to the Java arguments could fix the issue.
I don't have an Office 365 to test, so it's pure guesswork.

**Comment by ahmedmagdiosman** [comment]
That could be possible. I'm not so familiar with current Java, so would it be sufficient to override  using --env the JAVA_OPTIONS from [sismics/docker-ubuntu-jetty](https://github.com/sismics/docker-ubuntu-jetty/blob/2f4dd6d1cd228401c1f9acff97e8d0e22e9095ba/Dockerfile#L23) or do I need to rebuild the base image (and subsequently teedy/docs)?

Also, thanks a lot for the quick replies and this nice project :)

**Comment by jendib** [comment]
Overriding JAVA_OPTIONS when you start the Docker container should work.

**Comment by ahmedmagdiosman** [comment]
Sadly that didn't work :( 
I confirmed that it was changed in the container.

BTW, there's two environment variables (JAVA_OPTS and JAVA_OPTIONS). I've tried both but no success :(

**Comment by ahmedmagdiosman** [comment]
It seems even though the parameters are being passed to the JVM, some of them are not being applied. I've added -Dmail.debug=true, but I'm only getting INFO logs.


``jcmd 1 VM.system_properties`` clearly shows it's there: 
````
awt.toolkit=sun.awt.X11.XToolkit
mail.debug=true
java.specification.version=11
sun.cpu.isalist=
sun.jnu.encoding=UTF-8
java.class.path=/opt/jetty/start.jar
java.vm.vendor=Oracle Corporation
mail.smtp.starttls.enable=true
sun.arch.data.model=64
mail.smtp.connectiontimeout=20000
sun.font.fontmanager=sun.awt.X11FontManager
java.vendor.url=http\://java.oracle.com/
user.timezone=Europe/Paris
jetty.base=/opt/jetty
jetty.home=/opt/jetty
java.vm.specification.version=11
os.name=Linux
sun.java.launcher=SUN_STANDARD
sun.boot.library.path=/usr/lib/jvm/java-11-openjdk-amd64/lib
sun.java.command=/opt/jetty/start.jar jetty.state\=/opt/jetty/jetty.state jetty-logging.xml jetty-started.xml
jdk.debug=release
sun.cpu.endian=little
user.home=/root
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
user.language=en
java.specification.vendor=Oracle Corporation
java.version.date=2019-01-15
java.home=/usr/lib/jvm/java-11-openjdk-amd64
mail.smtp.auth=true
file.separator=/
java.vm.compressedOopsMode=32-bit
line.separator=\n
java.specification.name=Java Platform API Specification
java.vm.specification.vendor=Oracle Corporation
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
java.runtime.version=11.0.2+9-Ubuntu-3ubuntu118.04.3
user.name=root
jetty.version=9.4.12.v20180830
path.separator=\:
os.version=4.19.0-0.bpo.5-amd64
java.runtime.name=OpenJDK Runtime Environment
file.encoding=UTF-8
java.vm.name=OpenJDK 64-Bit Server VM
java.vendor.url.bug=http\://bugreport.java.com/bugreport/
jetty.git.hash=27208684755d94a92186989f695db2d7b21ebc51
java.io.tmpdir=/tmp
jetty.tag.version=master
java.version=11.0.2
user.dir=/opt/jetty
os.arch=amd64
java.vm.specification.name=Java Virtual Machine Specification
java.awt.printerjob=sun.print.PSPrinterJob
````

**Comment by ahmedmagdiosman** [comment]
Hey there again,

I switched to gmail and I'm still having issues. Is there anywhere I can  see a sample configuration. I'm probably doing something wrong.

Here's my current config:

SMTP Host: smtp.gmail.com
STMP Port: 465
Username: example@gmail.com
Password: xxx
Sender email: example@gmail.com


````
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)
	at org.apache.commons.mail.Email.send(Email.java:1496)
	at com.sismics.util.EmailUtil.sendEmail(EmailUtil.java:159)
	at com.sismics.util.EmailUtil.sendEmail(EmailUtil.java:175)
	at com.sismics.docs.core.listener.async.PasswordLostAsyncListener.lambda$on$0(PasswordLostAsyncListener.java:49)
	at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:47)
	at com.sismics.docs.core.listener.async.PasswordLostAsyncListener.on(PasswordLostAsyncListener.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465, response: -1
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2197)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)
	... 15 more
````

With TLS
STMP Port: 587

````
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:587
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)
	at org.apache.commons.mail.Email.send(Email.java:1496)
	at com.sismics.util.EmailUtil.sendEmail(EmailUtil.java:159)
	at com.sismics.util.EmailUtil.sendEmail(EmailUtil.java:175)
	at com.sismics.docs.core.listener.async.PasswordLostAsyncListener.lambda$on$0(PasswordLostAsyncListener.java:49)
	at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:47)
	at com.sismics.docs.core.listener.async.PasswordLostAsyncListener.on(PasswordLostAsyncListener.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. a2sm5246846wrt.45 - gsmtp

	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2358)
	at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1823)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1300)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)
	... 15 more
````

**Comment by j1gg3** [comment]
same issue here, did you manage to solve it?

**Comment by ahmedmagdiosman** [comment]
Nope. I've tried with multiple providers and it seems to be an issue with Teedy itself.

**Comment by jendib** [comment]
If any of you can find where the problem come from, or even better provide a pull request, I could merge it.

**Comment by lukas-runge** [comment]
I can confirm that this is still an issue. I am also not able to send any mails out whatsoever.
Would be cool to see a fix for it.
Otherwise - thanks for the cool service!!!

Kind regards
@lukas-runge

**Comment by j1gg3** [comment]
I think this comes from:

Password Reset Mail: missing BASE URL → generated mails contain no valid reset link. You need to view email sourcecode to see
<a href="/#/passwordreset/SOMEHASHVALUE">Click here to reset your password</a> 
instead of

<a href="dms.yourdomain.de/#/passwordreset/SOMEHASHVALUE">Click here to reset your password</a>

**Comment by jendib** [comment]
It's indeed a totally separate issue, which is simply that the `DOCS_BASE_URL` env variable is missing in this case. It needs to be set as instructed here: https://github.com/sismics/docs#install-with-docker
