### ISSUE TITLE
Can't delete old documents

### ISSUE THREAD

**Issue by j1gg3** [sismics/docs#429]
As of I try to upload new documents, I can see the document gets processed but later on it is not available and docs just says "File not found".

![image](https://user-images.githubusercontent.com/34888046/86144163-9a7f2880-baf5-11ea-8ad2-831bb24dc243.png)

Docs Version v1.9
Postgres V. 9.6 

I also tried to set up a completeley new DB unfortunately I got the same error - see below:

`caused by:
org.postgresql.util.PSQLException: Bad value for type long : my super hidden text OCR text doc has been processed successfully but file is not visible <<<<<<
	at org.postgresql.jdbc.PgResultSet.toLong(PgResultSet.java:2873)
	at org.postgresql.jdbc.PgResultSet.getLong(PgResultSet.java:2099)
	at org.postgresql.jdbc.PgResultSet.getClob(PgResultSet.java:459)
	at org.postgresql.jdbc.PgResultSet.getClob(PgResultSet.java:445)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getClob(NewProxyResultSet.java:4371)
	at org.hibernate.type.descriptor.sql.ClobTypeDescriptor$1.doExtract(ClobTypeDescriptor.java:44)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:261)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:247)
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:333)
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3007)
	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1746)
	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1672)
	at org.hibernate.loader.Loader.getRow(Loader.java:1561)
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:731)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:990)
	at org.hibernate.loader.Loader.doQuery(Loader.java:948)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:340)
	at org.hibernate.loader.Loader.doList(Loader.java:2689)
	at org.hibernate.loader.Loader.doList(Loader.java:2672)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2506)
	at org.hibernate.loader.Loader.list(Loader.java:2501)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:504)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:395)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:220)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1508)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1537)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1505)
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1553)
	at com.sismics.docs.core.dao.FileDao.getFile(FileDao.java:84)
	at com.sismics.docs.rest.resource.FileResource.findFile(FileResource.java:755)
	at com.sismics.docs.rest.resource.FileResource.versions(FileResource.java:483)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.sismics.util.filter.SecurityFilter.doFilter(SecurityFilter.java:134)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.sismics.util.filter.SecurityFilter.doFilter(SecurityFilter.java:134)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.sismics.util.filter.RequestContextFilter.doFilter(RequestContextFilter.java:89)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.sismics.util.filter.CorsFilter.doFilter(CorsFilter.java:39)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by jendib** [comment]
Do you have this problem only with specific files?

**Comment by j1gg3** [comment]
> Do you have this problem only with specific files?

tried with pdf, png and jpeg with same resulst / issue.

**Comment by j1gg3** [comment]
Any idea on this?

I tried again with postgres V 9.5 as DB, unfortunately with the same result.

`

03.07.20 13:11 | SqlExceptionHelper | SQL Error: 0, SQLState: 22003
-- | -- | --
03.07.20 13:11 | DocumentCreatedAsyncListener | Document created event: DocumentCreatedAsyncEvent{documentId=911fae1b-ff6b-4599-a63a-54c3382aaf61}
03.07.20 13:11 | FileUtil | Processing ended for file: 0ef2d224-dd0f-4fb0-9176-c0c3ec3be316
03.07.20 13:11 | FileProcessingAsyncListener | File content extracted in 156ms: 0ef2d224-dd0f-4fb0-9176-c0c3ec3be316
03.07.20 13:11 | FileProcessingAsyncListener | Start extracting content from: File{id=0ef2d224-dd0f-4fb0-9176-c0c3ec3be316, name=Checkliste_ Unterlagenverzeichnis Fam. Muharemovic.pdf}
03.07.20 13:11 | ClasspathScanner | Found 7 classes for FormatHandler
03.07.20 13:11 | FileProcessingAsyncListener | File created event: FileCreatedAsyncEvent{fileId=0ef2d224-dd0f-4fb0-9176-c0c3ec3be316, language=null}
03.07.20 13:11 | FileUtil | Processing started for file: 0ef2d224-dd0f-4fb0-9176-c0c3ec3be316
03.07.20 13:11 | ClasspathScanner | Found 1 classes for AuthenticationHandler
03.07.20 13:11 | InboxService | Inbox service starting up
03.07.20 13:11 | FileService | File service starting up
03.07.20 13:11 | LuceneIndexingHandler | Checking index health and version
03.07.20 13:11 | LuceneIndexingHandler | Using file Lucene storage: /data/lucene
03.07.20 13:11 | ClasspathScanner | Found 1 classes for IndexingHandler
03.07.20 13:11 | EMF | Configuring EntityManager from environment parameters
03.07.20 13:11 | DbOpenHelper | Database upgrade complete
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-025-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-024-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-023-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-022-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-021-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-020-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-019-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-018-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-017-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-016-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-015-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-014-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-013-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-012-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-011-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-010-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-009-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-008-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-007-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-006-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-005-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-004-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-003-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-002-0.sql
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-001-0.sql
03.07.20 13:11 | DbOpenHelper | Found database version 0, new version is 25, executing database incremental update scripts
03.07.20 13:11 | DbOpenHelper | Executing script: dbupdate-000-0.sql
03.07.20 13:11 | DbOpenHelper | Executing initial schema creation script
03.07.20 13:11 | DbOpenHelper | Unable to get database version: Table T_CONFIG not found
03.07.20 13:11 | DbOpenHelper | Opening database and executing incremental updates
03.07.20 13:11 | EMF | Configuring EntityManager from environment parameters
03.07.20 13:11 | RequestContextFilter | Using base data directory: /data

`

**Comment by j1gg3** [comment]
oh wait, I figured out Version 1.9 has not yet been released as a stable one, therefore I rolled back to Version 1.8. I was wondering about the versioning in the docker hub repo, so how to figure out which is version 1.8?  you are calling your images travis-596  :-)



**I am able to upload new documents with v1.8 but the old errors are still present. Can you tell me how to elminate them? I tried to delete old entries but without success.**

**Comment by jendib** [comment]
The Docker images are properly named with tag versions, please see the `README.md`.

For your specific problem I don't know, never had this issue with PgSQL.
