### ISSUE TITLE
java.lang.IllegalStateException: Config parameter not found: SMTP_PORT

### ISSUE THREAD

**Issue by cream68** [sismics/docs#518]
I setup `DOCS_SMTP_HOSTNAME`, `DOCS_SMTP_PORT`, `DOCS_SMTP_USERNAME` and `DOCS_SMTP_PASSWORD` for my docker container, but it get the error

`java.lang.IllegalStateException: Config parameter not found: SMTP_PORT`

Does anyone know how to fix this?

**Comment by jendib** [comment]
full stack trace needed to investigate

**Comment by jaredraycoleman** [comment]
I'm getting the same error (Also running in a docker container and setting the environment variables):

`java.lang.IllegalStateException: Config parameter not found: SMTP_PORT
        at com.sismics.docs.core.util.ConfigUtil.getConfigStringValue(ConfigUtil.java:26)
        at com.sismics.docs.core.util.ConfigUtil.getConfigIntegerValue(ConfigUtil.java:48)
        at com.sismics.util.EmailUtil.sendEmail(EmailUtil.java:103)
        at com.sismics.util.EmailUtil.sendEmail(EmailUtil.java:181)
        at com.sismics.docs.core.listener.async.PasswordLostAsyncListener.lambda$on$0(PasswordLostAsyncListener.java:49)
        at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:47)
        at com.sismics.docs.core.listener.async.PasswordLostAsyncListener.on(PasswordLostAsyncListener.java:40)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by dbeiner** [comment]
Same issue here...

**Comment by vmario89** [comment]
guess you can do sth. like `docker exec -it <docker_database_container> bash` and then execute the sql queries to add missing values in your psql db. 

https://github.com/sismics/docs/search?q=SMTP_PORT i did not find anything in https://github.com/sismics/docs/tree/master/docs-core/src/main/resources/db/update, so it seems those values get written on the fly when first used by jetty or so. some other values like LDAP_* get created by those update scripts.

the following entries i have in database table "t_config"

![grafik](https://user-images.githubusercontent.com/5631071/234941823-ebcb7169-2654-4509-a626-5e2af452062b.png)

you can simple insert them, maybe with some trash value. then at least the application should stop throwing erros and you can go ahead configuring your instance

**Comment by vmario89** [comment]
ps: might also be a real bug. I am not sure what the correct mechanism will be for SMTP settings

**Comment by vmario89** [comment]
ah sorry for the third comment in a row. as this ticket is closed, maybe reopen it or create a new one please.

**Comment by dbeiner** [comment]
Thanks for your help @vmario89 !

This works : 

//Connect to database (docker container)
psql "postgres://user:password@host:port/database_name"

//Show content of t_config table
select * from t_config;

//Insert SMTP parameters into the database
INSERT INTO "t_config" ("cfg_id_c", "cfg_value_c") VALUES ('SMTP_PORT','port');
INSERT INTO "t_config" ("cfg_id_c", "cfg_value_c") VALUES ('SMTP_HOSTNAME','smtp_host');
INSERT INTO "t_config" ("cfg_id_c", "cfg_value_c") VALUES ('SMTP_FROM','sender_email');

**Comment by jendib** [comment]
It's strange that those entries in t_config disappeared.

**Comment by dbeiner** [comment]
There are a lot of missing entries in my database compared to your screenshot. It's strange...

![image](https://user-images.githubusercontent.com/50744242/235148810-de3cd505-d616-454a-8400-ec89a1136f18.png)

**Comment by dbeiner** [comment]
> It's strange that those entries in t_config disappeared.

Je pense qu'elles n'ont jamais été créées malgré une stack docker toute neuve...
