### ISSUE TITLE
h2database upgrade causing failure on launch.

### ISSUE THREAD

**Issue by Nedlinin** [sismics/docs#520]
So the h2database library update from a couple weeks back caused my instance of teedy to be unable to start.

https://github.com/sismics/docs/commit/6fcd8771a5e15cd16b8b4f35ae01520eb0c87865#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R31

This upgrade to .200 apparently is known to uncover an issue with an apparently slightly corrupted database that the previous versions would happily skip over the inconsistency.  https://github.com/h2database/h2database/issues/2078

The seemingly proposed solution is backing up the database using the old lib, creating a new db with the new lib and loading the backup into it.  

```
12 Feb 2021 14:19:49,248 WARN com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$WarnLogger.log(Slf4jMLog.java:220) Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@60a19573 is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/tmp/jetty-0_0_0_0-8080-docs_war-_-any-16950265786861505824/webapp/WEB-INF/lib/jaxb-impl-2.3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-02-12 14:19:52.046:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@31190526{Teedy,/,file:///tmp/jetty-0_0_0_0-8080-docs_war-_-any-16950265786861505824/webapp/,UNAVAILABLE}{./webapps/docs.war}
org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
        at org.eclipse.jetty.start.Main.start(Main.java:491)
        at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by:
java.sql.SQLException: Connections could not be acquired from the underlying database!
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:173)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:447)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:785)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:754)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
        at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
Caused by:
java.lang.IllegalStateException: Unsupported type 17 [1.4.200/3]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.type.ObjectDataType.newType(ObjectDataType.java:165)
        at org.h2.mvstore.type.ObjectDataType.read(ObjectDataType.java:229)
        at org.h2.mvstore.type.ObjectDataType.read(ObjectDataType.java:114)
        at org.h2.mvstore.Page.read(Page.java:605)
        at org.h2.mvstore.Page.read(Page.java:239)
        at org.h2.mvstore.MVStore.readPage(MVStore.java:2211)
        at org.h2.mvstore.MVMap.readPage(MVMap.java:672)
        at org.h2.mvstore.MVMap.readOrCreateRootPage(MVMap.java:688)
        at org.h2.mvstore.MVMap.setRootPos(MVMap.java:682)
        at org.h2.mvstore.MVStore.openMap(MVStore.java:576)
        at org.h2.mvstore.MVStore.openMap(MVStore.java:535)
        at org.h2.mvstore.MVStore.openMap(MVStore.java:516)
        at org.h2.mvstore.MVStore.removeMap(MVStore.java:2742)
        at org.h2.engine.Database.handleUpgradeIssues(Database.java:866)
        at org.h2.engine.Database.open(Database.java:742)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
```

**Comment by jendib** [comment]
That's a bit unfortunate, I would prefer users to have a seamless upgrade. Maybe I should downgrade to .199

**Comment by Nedlinin** [comment]
Your call obviously.  In my case I downgraded to an older version and was (thankfully) able to continuing using the same database without it being toast.  Reminded me I should really do better about backups!

Anyway, it does appear .199 is unaffected by this.  Another possible option might be to have a migration script to detect the older version, kick off the script to do the dump/recreate?  I'm unfamiliar with the actual code behind this project so I have no idea how tough this might be to implement.  I'm just a happy user :)

**Comment by jendib** [comment]
Backup/restore is too much for an auto upgrade (some people have massive database).
By the way you should only use the versioned Docker images, not the master (unstable) branch ;)

**Comment by Nedlinin** [comment]
> Backup/restore is too much for an auto upgrade (some people have massive database).

Fair enough!  I just started using earlier this year so my database is tiny still :)

> By the way you should only use the versioned Docker images, not the master (unstable) branch ;)

I'm one of those that understands things will break on the bleeding edge thankfully.  I run diun to get container update notifications and test them out on the weekends when I'm bored.  Figure if I can help point out some issues before it hits the general userbase I might as well.  But, point taken either way!

Appreciate the work on the project!

**Comment by jendib** [comment]
Thanks for testing then, I was actually waiting for some feedback on those libs upgrade 👍
