### ISSUE TITLE
Issue with overnight crashing

### ISSUE THREAD

**Issue by campbellmcgregor** [sismics/docs#523]
Hello,
My install of Teddy runs perfectly then overnight it will stop functioning. Jetty is running as I get a list of directories but Teddy is not there. I pulled the log file for last night and there is a few errors that I am not understanding. Is there any chance I can get an expert eye over this please?

`5 Feb 2021 23:58:53,491 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:92) 0 messages found 
25 Feb 2021 23:59:53,495 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:82) Synchronizing IMAP inbox... 
25 Feb 2021 23:59:53,676 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:92) 0 messages found 
26 Feb 2021 00:00:53,681 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:82) Synchronizing IMAP inbox... 
26 Feb 2021 00:00:53,686 ERROR com.sismics.docs.core.service.InboxService.runOneIteration(InboxService.java:68) Exception during inbox synching 
java.util.ServiceConfigurationError: javax.mail.Provider: Error accessing configuration file
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1173)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1206)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at javax.mail.Session.getProviderByProtocol(Session.java:1017)
	at javax.mail.Session.getProvider(Session.java:542)
	at javax.mail.Session.getStore(Session.java:620)
	at javax.mail.Session.getStore(Session.java:600)
	at com.sismics.docs.core.service.InboxService.openInbox(InboxService.java:180)
	at com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:90)
	at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:47)
	at com.sismics.docs.core.service.InboxService.syncInbox(InboxService.java:76)
	at com.sismics.docs.core.service.InboxService.runOneIteration(InboxService.java:66)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:224)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by jendib** [comment]
Closing for inactivity.
