### ISSUE TITLE
Build using Github Actions

### ISSUE THREAD

**Issue by jendib** [sismics/docs#541]
Migrate the CI to Gitlab Actions, Travis is deprecated.

**Comment by jendib** [comment]
No further work can be done unless this issue is solved. If someone has some spare time to look into it and provide a PR it would be greatly appreciated.

**Comment by dschaper** [comment]
What is needed for the GHA tasks? Upload of the WAR and ancillary files as a Release from the master branch on push to master branch? Any needs for Pull Requests? 

And then a docker image with Jetty serving the WAR? Does it need to be the existing base image or can a Java 11 with node/grunt for a base and then the existing required packages plus jetty? (I'm thinking maybe a multistage if needed, though if GHA builds the WAR then only a runtime docker container stage is needed.) Can do images to both GHCR and Docker Hub if needed/wanted.

I have the basis of an Action that builds everything but I need to work on the artifacts and the docker images.

Based on https://medium.com/@alexander.volminger/ci-cd-for-java-maven-using-github-actions-d009a7cb4b8f but I've only spent about 10 minutes on it.

```yaml
name: Maven CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn -Pprod -DskipTests clean install
```

Will PR when I have something worth looking at. The existing PR #564 fails for me and it doesn't upload any artifacts for release, it looks like it just builds docker images?

**Comment by dschaper** [comment]
Okay, I have a workflow that builds the main application. It creates the WAR and saves it as a build artifact and then creates and pushes a docker image with that WAR. The problem I'm running in to is that it builds and runs fine against the 1.9 tag but fails to run against 1.10-SNAPSHOT. 

```plain
Running Jetty:
2021-10-02 23:53:51.982:INFO::main: Logging initialized @557ms to org.eclipse.jetty.util.log.StdErrLog
2021-10-02 23:53:52.250:WARN:oejs.HomeBaseWarning:main: This instance of Jetty is not running from a separate {jetty.base} directory, this is not recommended.  See documentation at http://www.eclipse.org/jetty/documentation/current/startup.html
2021-10-02 23:53:52.306:INFO:oejs.Server:main: jetty-9.4.12.v20180830; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 11.0.8+10-post-Ubuntu-0ubuntu118.04.1
2021-10-02 23:53:52.324:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/jetty/webapps/] at interval 1
2021-10-02 23:53:53.718:WARN:oeja.AnnotationParser:main: Unknown asm implementation version, assuming version 393216
2021-10-02 23:53:53.789:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=70ms
2021-10-02 23:53:53.789:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@6ae5aa72{/,file:///tmp/jetty-0.0.0.0-8080-docs.war-_-any-7369655854988206878.dir/webapp/,UNAVAILABLE}{/docs.war}
MultiException[java.lang.RuntimeException: Error scanning file /tmp/jetty-0.0.0.0-8080-docs.war-_-any-7369655854988206878.dir/webapp/WEB-INF/classes/com/sismics/docs/rest/resource/ThemeResource$1.class, java.lang.RuntimeException: Error scanning file /tmp/jetty-0.0.0.0-8080-docs.war-_-any-7369655854988206878.dir/webapp/WEB-INF/classes/com/sismics/docs/rest/resource/RouteModelResource.class, java.lang.RuntimeException: Error scanning file /tmp/jetty-0.0.0.0-8080-docs.war-_-any-7369655854988206878.dir/webapp/WEB-INF/classes/com/sismics/docs/rest/resource/ThemeResource.class, java.lang.RuntimeException: Error scanning file /tmp/jetty-0.0.0.0-8080-docs.war-_-any-7369655854988206878.dir/webapp/WEB-INF/classes/com/sismics/docs/rest/resource/RouteModelResource$1.class]
        at org.eclipse.jetty.util.MultiException.ifExceptionThrow(MultiException.java:124)
        at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:506)
        at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:368)
        at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:517)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1454)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:847)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:505)
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:453)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:579)
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:240)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:416)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:383)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
        at org.eclipse.jetty.start.Main.start(Main.java:486)
        at org.eclipse.jetty.start.Main.main(Main.java:77)
Suppressed:
        |java.lang.RuntimeException: Error scanning file /tmp/jetty-0.0.0.0-8080-docs.war-_-any-7369655854988206878.dir/webapp/WEB-INF/classes/com/sismics/docs/rest/resource/ThemeResource$1.class
        |       at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:743)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:829)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        |       at java.base/java.lang.Thread.run(Thread.java:834)
        |Caused by:
        |java.lang.UnsupportedOperationException
        |       at org.objectweb.asm.ClassVisitor.visitNestHostExperimental(ClassVisitor.java:158)
        |       at org.objectweb.asm.ClassReader.accept(ClassReader.java:541)
        |       at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        |       at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:933)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:737)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:829)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        |       at java.base/java.lang.Thread.run(Thread.java:834)
Suppressed:
        |java.lang.RuntimeException: Error scanning file /tmp/jetty-0.0.0.0-8080-docs.war-_-any-7369655854988206878.dir/webapp/WEB-INF/classes/com/sismics/docs/rest/resource/RouteModelResource.class
        |       at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:743)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:829)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        |       at java.base/java.lang.Thread.run(Thread.java:834)
        |Caused by:
        |java.lang.UnsupportedOperationException
        |       at org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
        |       at org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
        |       at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        |       at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:933)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:737)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:829)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        |       at java.base/java.lang.Thread.run(Thread.java:834)
Suppressed:
        |java.lang.RuntimeException: Error scanning file /tmp/jetty-0.0.0.0-8080-docs.war-_-any-7369655854988206878.dir/webapp/WEB-INF/classes/com/sismics/docs/rest/resource/ThemeResource.class
        |       at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:743)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:829)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        |       at java.base/java.lang.Thread.run(Thread.java:834)
        |Caused by:
        |java.lang.UnsupportedOperationException
        |       at org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
        |       at org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
        |       at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        |       at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:933)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:737)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:829)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        |       at java.base/java.lang.Thread.run(Thread.java:834)
Suppressed:
        |java.lang.RuntimeException: Error scanning file /tmp/jetty-0.0.0.0-8080-docs.war-_-any-7369655854988206878.dir/webapp/WEB-INF/classes/com/sismics/docs/rest/resource/RouteModelResource$1.class
        |       at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:743)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:829)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        |       at java.base/java.lang.Thread.run(Thread.java:834)
        |Caused by:
        |java.lang.UnsupportedOperationException
        |       at org.objectweb.asm.ClassVisitor.visitNestHostExperimental(ClassVisitor.java:158)
        |       at org.objectweb.asm.ClassReader.accept(ClassReader.java:541)
        |       at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        |       at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:933)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:737)
        |       at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:829)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        |       at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        |       at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        |       at java.base/java.lang.Thread.run(Thread.java:834)
Caused by:
java.lang.RuntimeException: Error scanning file /tmp/jetty-0.0.0.0-8080-docs.war-_-any-7369655854988206878.dir/webapp/WEB-INF/classes/com/sismics/docs/rest/resource/ThemeResource$1.class
        at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:743)
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:829)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by:
java.lang.UnsupportedOperationException
        at org.objectweb.asm.ClassVisitor.visitNestHostExperimental(ClassVisitor.java:158)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:541)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:933)
        at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:737)
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:829)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-10-02 23:53:53.825:INFO:oejs.AbstractConnector:main: Started ServerConnector@2ad48653{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2021-10-02 23:53:53.827:INFO:oejs.Server:main: Started @2401ms
```

I haven't set up the importer builds or tags other than `latest`, so that is next. Below is the workflow I have for now and will PR it when it is more fleshed out to handle tags properly. I'll try to do a Docker Hub and GHCR build for both registries.

```yaml
name: Maven CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "maven"
      - name: Build with Maven
        run: mvn -Pprod -DskipTests clean install
      - name: Upload war artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs.war
          path: docs-web/target/*.war

  build_docker_image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_publish]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download war artifact
        uses: actions/download-artifact@v2
        with:
          name: docs.war
          path: docs-web/target
      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docs:latest
```

**Comment by dschaper** [comment]
@jendib Still interest in this issue?

**Comment by dschaper** [comment]
I've got something working and building 1.10 in docker images. It seems that logins are broken for some reason, passwords are not accepted. That may be from the change of the base image to an official Jetty 9. Are there any packages besides the ones in the Dockerfile that need to be added to the running configuration?

**Comment by jendib** [comment]
Why not keep using `sismics/ubuntu-jetty:9.4.12-2` base image? It's a public image pushed to Docker Hub (source here: https://github.com/sismics/docker-ubuntu-jetty).

**Comment by dschaper** [comment]
Because version 1.10 doesn't work with that image.

**Comment by dschaper** [comment]
And in case it helps, this is the environment inside the docker container:

```plain
            "Env": [
                "PATH=/usr/local/jetty/bin:/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "JAVA_HOME=/usr/local/openjdk-11",
                "LANG=C.UTF-8",
                "JAVA_VERSION=11.0.12",
                "JETTY_VERSION=9.4.44.v20210927",
                "JETTY_HOME=/usr/local/jetty",
                "JETTY_BASE=/var/lib/jetty",
                "TMPDIR=/tmp/jetty",
                "JETTY_TGZ_URL=https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-home/9.4.44.v20210927/jetty-home-9.4.44.v20210927.tar.gz",
                "JETTY_GPG_KEYS=AED5EE6C45D0FE8D5D1B164F27DED4BF6216DB8F \t2A684B57436A81FA8706B53C61C3351A438A3B7D \t5989BAF76217B843D66BE55B2D0E1FB8FE4B68B4 \tB59B67FD7904984367F931800818D9D68FB67BAC \tBFBB21C246D7776836287A48A04E0C74ABB35FEA \t8B096546B1A8F02656B15D3B1677D141BCF3584D \tFBA2B18D238AB852DF95745C76157BDF03D0DCD6 \t5C9579B3DB2E506429319AAEF33B071B29559E1E \tF254B35617DC255D9344BCFA873A8E86B4372146",
                "JAVA_OPTIONS=-Xmx1g"
            ],
            "Cmd": [
                "java",
                "-jar",
                "/usr/local/jetty/start.jar"
            ],
```

**Comment by jendib** [comment]
@dschaper Did you manage to get something working? Thanks

**Comment by jendib** [comment]
@dschaper I fixed the default admin password (DOCS_ADMIN_PASSWORD_INIT unset) and other long standing issues.

I also upgraded the base Jetty image to 9.4.36 so everything is working nicely now.

If you have time to continue the Github Actions work that would be great.

**Comment by dschaper** [comment]
Thanks for the update. I'll take a look and see if I can get things going again!

**Comment by dschaper** [comment]
@jendib Can you assign this issue to me? Then it will show on my worklist and I won't overlook it.
