### ISSUE TITLE
SMTP config error

### ISSUE THREAD

**Issue by djjudas21** [sismics/docs#559]
Hi there. I've deployed Teedy into Kubernetes using the [k8sathome Helm chart](https://github.com/k8s-at-home/charts/tree/master/charts/stable/teedy) but I'm unable to get the SMTP config working for password resets etc.

The container is erroring with

```
java.lang.IllegalStateException: Config parameter not found: SMTP_PORT
	at com.sismics.docs.core.util.ConfigUtil.getConfigStringValue(ConfigUtil.java:26)
	at com.sismics.docs.core.util.ConfigUtil.getConfigIntegerValue(ConfigUtil.java:48)
	at com.sismics.util.EmailUtil.sendEmail(EmailUtil.java:102)
	at com.sismics.util.EmailUtil.sendEmail(EmailUtil.java:180)
	at com.sismics.docs.core.listener.async.PasswordLostAsyncListener.lambda$on$0(PasswordLostAsyncListener.java:49)
	at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:47)
	at com.sismics.docs.core.listener.async.PasswordLostAsyncListener.on(PasswordLostAsyncListener.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I've checked your [docs about environment variables](https://github.com/sismics/docs#available-environment-variables) and this is what my environment looks like, to talk to a local, open/unauthenticated SMTP server

```
$ kubectl describe pod teedy-748f8f589b-gh24p | grep SMTP
      DOCS_SMTP_HOSTNAME:        smtp.mydomain.com
      DOCS_SMTP_PASSWORD:        
      DOCS_SMTP_PORT:            25
      DOCS_SMTP_USERNAME:        
```

And this environment is set up by supplying the following `values.yaml` to Helm:

```
$ cat values.yaml  | grep SMTP
  # --  Hostname of the SMTP-Server to be used by Teedy
  DOCS_SMTP_HOSTNAME: smtp.mydomain.com
  # -- The port of the SMTP-Server which should be used
  DOCS_SMTP_PORT: 25
  # -- The username of the SMTP-Server which should be used
  DOCS_SMTP_USERNAME: ""
  # -- The password of the SMTP-Server which should be used
  DOCS_SMTP_PASSWORD: ""
```

**Comment by jendib** [comment]
What is the content of your T_CONFIG table?
