### ISSUE TITLE
Email syncing stops working

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#572]
Hi,
in one of my Teedy instances syncing mailbox just stopped working and i really dont know why. i checked the mail logs and i was not able to get a clue. the error always occures if the target mailbox contains one or more unread mails. if zero unread mails are there, no error is thrown. do you have an idea what i could do? might it be an issue with changing to mail to "read" state after downloading it?

```
6 Sep. 2021 00:18:06,991 INFO com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:82) Synchronizing IMAP inbox... 
06 Sep. 2021 00:18:07,178 ERROR com.sismics.docs.core.service.InboxService.runOneIteration(InboxService.java:68) Exception during inbox synching 
java.lang.NoClassDefFoundError: javax/activation/DataSource
	at com.sun.mail.imap.IMAPFolder.newIMAPMessage(IMAPFolder.java:1395)
	at com.sun.mail.imap.MessageCache.getMessage(MessageCache.java:146)
	at com.sun.mail.imap.MessageCache.getMessageBySeqnum(MessageCache.java:172)
	at com.sun.mail.imap.IMAPFolder.getMessageBySeqNumber(IMAPFolder.java:4023)
	at com.sun.mail.imap.IMAPFolder.getMessagesBySeqNumbers(IMAPFolder.java:4041)
	at com.sun.mail.imap.IMAPFolder.search(IMAPFolder.java:2377)
	at com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:91)
	at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:32)
	at com.sismics.docs.core.service.InboxService.syncInbox(InboxService.java:76)
	at com.sismics.docs.core.service.InboxService.runOneIteration(InboxService.java:66)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:224)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more
```

**Comment by vmario89** [comment]
some more info:
error is not dependent of java version. i removed jdk 11 and installed version 8. still happens


the background log from Teedy looks like this:
```
20.09.21 13:20 | InboxService | Exception during inbox synching
-- | -- | --
20.09.21 13:20 | InboxService | Importing message: test
20.09.21 13:20 | InboxService | 1 messages found
```

means connection to imap is fine (credentials work), inbox is found, message is found, but message cannot be pulled into Teedy

**Comment by vmario89** [comment]
![grafik](https://user-images.githubusercontent.com/5631071/133996539-3a1d3c24-fa4b-495e-9e03-626f418f06b2.png)
seen that it says "No login methods supported!" 

makes no sense. dovecot mail server log says:
`
imap-login: Login: user=<REDACTED>, method=PLAIN, rip=94.16.107.95, lip=94.16.107.95, mpid=5887, secured, session=<cqF3x2vMlpJeEGtf>`

**Comment by vmario89** [comment]
okay that warning came from jdk 1.8.0; installing 1.11 again that disappeared

**Comment by vmario89** [comment]
updating to latest teedy did not work either.

i also tried to add to pom.xml in docs-core / docs-web:

```
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
        </dependency>
```

stll error:

```
java.lang.NoClassDefFoundError: javax/activation/DataSource
	at com.sun.mail.imap.IMAPFolder.newIMAPMessage(IMAPFolder.java:1395)
	at com.sun.mail.imap.MessageCache.getMessage(MessageCache.java:146)
	at com.sun.mail.imap.MessageCache.getMessageBySeqnum(MessageCache.java:172)
	at com.sun.mail.imap.IMAPFolder.getMessageBySeqNumber(IMAPFolder.java:4023)
	at com.sun.mail.imap.IMAPFolder.getMessagesBySeqNumbers(IMAPFolder.java:4041)
	at com.sun.mail.imap.IMAPFolder.search(IMAPFolder.java:2377)
	at com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:91)
	at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:32)
	at com.sismics.docs.core.service.InboxService.syncInbox(InboxService.java:76)
	at com.sismics.docs.core.service.InboxService.runOneIteration(InboxService.java:66)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:221)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more

```

**Comment by vmario89** [comment]
finally found the problem. no need to adjust pom.xml files. It was the Jetty version. I rolled back to previous version but no change. After playing with libs i found the fix:

```
cd /opt/jetty-distribution-9.4.43.v20210629/lib/mail
rm mv javax.mail.glassfish-1.4.1.v201005082020.jar
wget https://repo1.maven.org/maven2/com/sun/mail/javax.mail/1.6.1/javax.mail-1.6.1.jar
wget https://repo1.maven.org/maven2/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar
chown jetty:jetty *.jar
```
