### ISSUE TITLE
Error reading JPEG image in PDF file

### ISSUE THREAD

**Issue by jendib** [sismics/docs#59]
```
java.lang.IllegalArgumentException: Numbers of source Raster bands and source color space components do not match
        at java.awt.image.ColorConvertOp.filter(ColorConvertOp.java:482)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.acceptPixels(JPEGImageReader.java:1263)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImage(Native Method)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1231)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1034)
        at javax.imageio.ImageReader.read(ImageReader.java:940)
        at org.apache.pdfbox.filter.DCTFilter.decode(DCTFilter.java:83)
        at org.apache.pdfbox.cos.COSInputStream.create(COSInputStream.java:69)
        at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:163)
        at org.apache.pdfbox.pdmodel.common.PDStream.createInputStream(PDStream.java:234)
        at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.<init>(PDImageXObject.java:144)
        at org.apache.pdfbox.pdmodel.graphics.PDXObject.createXObject(PDXObject.java:69)
        at org.apache.pdfbox.pdmodel.PDResources.getXObject(PDResources.java:385)
        at org.apache.pdfbox.contentstream.operator.graphics.DrawObject.process(DrawObject.java:53)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:814)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:471)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:445)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:149)
        at org.apache.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:179)
        at org.apache.pdfbox.rendering.PDFRenderer.renderPage(PDFRenderer.java:208)
        at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:139)
        at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:68)
        at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:55)
        at com.sismics.docs.core.util.PdfUtil.renderFirstPage(PdfUtil.java:242)
        at com.sismics.docs.core.util.FileUtil.saveVariations(FileUtil.java:127)
        at com.sismics.docs.core.util.FileUtil.save(FileUtil.java:108)
        at com.sismics.docs.rest.resource.FileResource.add(FileResource.java:157)
```

**Comment by ErickPezoa** [comment]
I am having this problem when using PDFBOX with the class PDImageXObject. Is there a fix yet?

**Comment by jendib** [comment]
You just need TwelveMonkeys plugin in your classpath, it's automatically registered.
