### ISSUE TITLE
DELETE /document/id should return 404 for non existing document

### ISSUE THREAD

**Issue by alexanderadam** [sismics/docs#620]
I'm trying to use a libcurl based client to make some API calls (i.e. deleting a document) to Teedy v1.9 but I'm getting `500` error back.

The Document ID doesn't exist, therefore I would naturally expect a `404` (or at least `200` since the state of deletion is somehow fulfilled).
Is this message somehow expected?

```
# Request
Found bundle for host teedy.url.tld: 0x7f9027715ed0 [can pipeline]
Could pipeline, but not asked to!
Re-using existing connection! (#0) with host teedy.url.tld
Connected to teedy.url.tld (123.456.789.1) port 443 (#0)
DELETE /api/document/somelong-id12-3456-7890-foo123456789 HTTP/1.1
Host: teedy.url.tld
Accept: */*
Cookie: auth_token=sometoken-1234-5678-9012-cookie123456
Accept-Encoding: application/json
Content-Type: application/json

# Response
HTTP/1.1 500 Server Error
Server: nginx/1.21.3
Date: Mon, 14 Feb 2022 13:30:05 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Keep-Alive,User-Agent,Cache-Control,X-Requested-With,If-Modified-Since,Accepts,X-Authenticated-User
Strict-Transport-Security: max-age=0

Connection #0 to host teedy.url.tld left intact
```

This is how the body looks like
```
14 Feb 2022 10:43:11,078 ERROR com.sismics.util.filter.RequestContextFilter.doFilter(RequestContextFilter.java:95) An exception occured, rolling back current transaction
javax.servlet.ServletException: javax.persistence.NoResultException: No entity found for query
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:432)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.sismics.util.filter.SecurityFilter.doFilter(SecurityFilter.java:134)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.sismics.util.filter.SecurityFilter.doFilter(SecurityFilter.java:134)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.sismics.util.filter.RequestContextFilter.doFilter(RequestContextFilter.java:89)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.sismics.util.filter.CorsFilter.doFilter(CorsFilter.java:39)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jendib** [comment]
It should return 404 you are right. An existence check should be done here: https://github.com/sismics/docs/blob/master/docs-web/src/main/java/com/sismics/docs/rest/resource/DocumentResource.java#L1002

**Comment by alexanderadam** [comment]
Wow, this is the first response I got from you!
Thank you!

**Comment by jendib** [comment]
Cannot be reproduced on latest version:
```
curl -vvv -X DELETE -H "Cookie: auth_token=9d720760-3b94-4653-a819-76ba6c79ce63" https://demo.teedy.io/api/document/69b79238-84bb-4263-a32f-9cbdf8c92188
*   Trying 94.23.194.181:443...
* TCP_NODELAY set
* Connected to demo.teedy.io (94.23.194.181) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.teedy.io
*  start date: Apr  1 03:00:15 2022 GMT
*  expire date: Jun 30 03:00:14 2022 GMT
*  subjectAltName: host "demo.teedy.io" matched cert's "*.teedy.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> DELETE /api/document/69b79238-84bb-4263-a32f-9cbdf8c92188 HTTP/1.1
> Host: demo.teedy.io
> User-Agent: curl/7.68.0
> Accept: */*
> Cookie: auth_token=9d720760-3b94-4653-a819-76ba6c79ce63
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Connection: close
< Cache-Control: no-cache
< Expires: 0
< Server: Jetty(9.4.36.v20210114)
<
* TLSv1.2 (IN), TLS alert, close notify (256):
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
```
