### ISSUE TITLE
Mail sync does not work for 1.12dev

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#675]
Hi,
based on the recent sismics docs version at master branch, i was able to successfully compile and run Teedy. But at least i have some issue to sync with mailboxes, because i get "No login methods supported!"

```
16 Apr. 2023 18:06:13,134 ERROR com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:100) Error syncing the inbox 
javax.mail.MessagingException: No login methods supported!;
  nested exception is:
	com.sun.mail.iap.ProtocolException: No login methods supported!
	at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:731)
	at javax.mail.Service.connect(Service.java:366)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:267)
	at com.sismics.docs.core.service.InboxService.openInbox(InboxService.java:181)
	at com.sismics.docs.core.service.InboxService.lambda$syncInbox$0(InboxService.java:90)
	at com.sismics.docs.core.util.TransactionUtil.handle(TransactionUtil.java:47)
	at com.sismics.docs.core.service.InboxService.syncInbox(InboxService.java:76)
	at com.sismics.docs.core.service.InboxService.runOneIteration(InboxService.java:66)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:233)
	at com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:103)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.sun.mail.iap.ProtocolException: No login methods supported!
	at com.sun.mail.imap.IMAPStore.authenticate(IMAPStore.java:921)
	at com.sun.mail.imap.IMAPStore.login(IMAPStore.java:817)
	at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:698)
	... 16 more

```

The ui config is:
![image](https://user-images.githubusercontent.com/5631071/232345431-50aa7cac-d027-48f0-be55-89f844b4777b.png)

i guess there are missing some settings to define SSL or STARTTLS settings. I use a mail server which is highly secure, using TLS 1.3, everything encrypted, etc. - but the settings basically work in Sismics Docs 1.11 on another server - so i guess some old code base worked in the older release. I remember some mail issues in the past, because some libraries made trouble. Have no clue yet

**Comment by jendib** [comment]
In the past I had to remove the javax.mail lib included with Jetty to replace it with a newer one. However in Jetty 11 it seems that they removed the included one. From your stacktrace your server is using the right lib. I'm not sure what is the issue here.

**Comment by vmario89** [comment]
fixed my problem with https://github.com/sismics/docs/pull/682

**Comment by vmario89** [comment]
btw related to https://serverfault.com/questions/667562/com-sun-mail-iap-protocolexception-no-login-methods-supported
