### ISSUE TITLE
Database file locked error

### ISSUE THREAD

**Issue by professor-farnsworth** [sismics/docs#680]
Hi All,

I'm using docker v1.11 and yesterday started getting the below error from the container logs, and the site is throwing 503 unavailable.

The problem seems to be the H2 db file is locked? IllegalStateException: The file is locked: nio:/data/db/docs.mv.db [1.4.199/7]

Things were working a few days ago, and I'm pretty sure the container hasn't been updated, docker hub shows it was tagged a month ago. Any ideas what the problem is? I tried using a backup of the database files from a few days ago with no luck.

_19 Apr 2023 17:05:05,527 INFO com.sismics.util.filter.RequestContextFilter.init(RequestContextFilter.java:43) Using base data directory: /data 
19 Apr 2023 17:05:05,556 INFO com.sismics.util.jpa.EMF.getEntityManagerProperties(EMF.java:83) Configuring EntityManager from environment parameters 
19 Apr 2023 17:05:37,045 WARN com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$WarnLogger.log(Slf4jMLog.java:223) com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@4e3c0d6f -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:  
**org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-199]**
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:193)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
...
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
**Caused by: java.lang.IllegalStateException: The file is locked: nio:/data/db/docs.mv.db [1.4.199/7]**
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)

	... 23 more
**Caused by: java.nio.channels.OverlappingFileLockException**
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1154)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1165)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)

	... 26 more_

**Comment by vmario89** [comment]
i did not try this for a while, but it should be recent enough -> https://stadtfabrikanten.org/display/TEED/Teedy+1.9+Migration+from+H2+to+PostgreSQL

**Comment by pepitoria** [comment]
I did something like what is described in the article mentioned by @vmario89. To be honest cannot remember all the details, this was around 2 years ago (being using teedy for 3 years now).

Sorry I cannot be of more help :/

**Comment by jendib** [comment]
It's not going to solve your issue but we should add clear information in the README.md that H2 is for demonstration only + a log message when starting Teedy with H2.

**Comment by professor-farnsworth** [comment]
Yeah, the readme mentions that H2 is used by default but postgres could be used for more performance. The default docker setup should probably be a compose file with postrgres used, then later on mention you can use H2 to test out with or if you really just need the smaller footprint. Using H2 really is prone to errors.

**Comment by jendib** [comment]
Sounds good, if anybody want to edit the README to reflect that.

**Comment by pepitoria** [comment]
just made this PR https://github.com/sismics/docs/pull/681
